#!/usr/bin/env bash
# CHECK THIS FILE INTO SOURCE CONTROL!

. "$(dirname "$0")/_/husky.sh"

[[ -e zip-deployboard-deck/node_modules/.bin/lint-staged ]] && cd zip-deployboard-deck; ./node_modules/.bin/lint-staged -p false
